@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NzY1OTUwMywiZXhwIjoxNzY3NzQ1OTAzfQ.8svW0RKiopc5CJzXEowLojhxsXcQDQpsCzRK6BDFYFY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NzY1OTUwMywiZXhwIjoxNzY4MjY0MzAzfQ.5gCBLVNlG9QgJMsTk8bkEX3L7YHfyUbAwRsTbH7SN1I

### 회원가입
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "user6@test.com",
    "name": "user4",
    "password": "password1"
}

### 로그인
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user6@test.com",
    "password": "password1"
}

### 토큰갱신
POST {{baseUrl}}/auth/refresh
Authorization: Bearer {{refreshToken}}

### 내 정보 조회
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

### 내 정보 수정
PATCH {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "alstn3@alstn.com",
  "name": "빙수",
  "currentPassword": "alstn123",
  "newPassword": "alstn1234",
  "profileImage": "https://example.com"
}


### 내가 참여중인 프로젝트 조회
GET {{baseUrl}}/users/me/projects
Authorization: Bearer {{accessToken}}

### 내가 참여중인 모든 프로젝트의 할 일 목록 조회
GET {{baseUrl}}/users/me/tasks
Authorization: Bearer {{accessToken}}

### 쿼리 추가 버전
GET {{baseUrl}}/users/me/tasks?from=2026-01-01&to=2026-01-31&project_id=1&status=todo&assignee_id=1&keyword=TODO
Authorization: Bearer {{accessToken}}

//날짜, 키워드 : ?from=2026-01-01&to=2026-01-31&keyword=진행
//users/me/tasks?from=2026-01-01&to=2026-01-31
//users/me/tasks?project_id=27
//users/me/tasks?status=todo
//users/me/tasks?from=2026-01-01&to=2026-01-31&project_id=27&status=todo&assignee_id=17&keyword=TODO
