### 회원가입
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "alstn4@alstn.com",
    "name": "민수",
    "password": "alstnalstn"

}

### 로그인
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "alstn3@alstn.com",
    "password": "alstn1234"
}

### 토큰갱신
POST http://localhost:3001/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzY4OSwiZXhwIjoxNzY3OTQyNDg5fQ.jyKeDQMimEQi4aYaFpgTX_tpazm7tVXhUYcy6Un_hpc

### 내 정보 조회
GET http://localhost:3001/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzcwNywiZXhwIjoxNzY3MzM5NTA3fQ.JOkVApBruJOFto5wxpgmWVlQIrs3kCMUQ4Js66I9RtA


### 내 정보 수정
PATCH http://localhost:3001/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzcwNywiZXhwIjoxNzY3MzM5NTA3fQ.JOkVApBruJOFto5wxpgmWVlQIrs3kCMUQ4Js66I9RtA
Content-Type: application/json

{
  "email": "alstn3@alstn.com",
  "name": "빙수",
  "currentPassword": "alstn123",
  "newPassword": "alstn1234",
  "profileImage": "https://example.com"
}


### 내가 참여중인 프로젝트 조회
GET http://localhost:3001/users/me/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzcwNywiZXhwIjoxNzY3MzM5NTA3fQ.JOkVApBruJOFto5wxpgmWVlQIrs3kCMUQ4Js66I9RtA

### 내가 참여중인 모든 프로젝트의 할 일 목록 조회
GET http://localhost:3001/users/me/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzcwNywiZXhwIjoxNzY3MzM5NTA3fQ.JOkVApBruJOFto5wxpgmWVlQIrs3kCMUQ4Js66I9RtA

### 쿼리 추가 버전
GET http://localhost:3001/users/me/tasks?from=2026-01-01&to=2026-01-31&project_id=27&status=todo&assignee_id=17&keyword=TODO
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NzMzNzcwNywiZXhwIjoxNzY3MzM5NTA3fQ.JOkVApBruJOFto5wxpgmWVlQIrs3kCMUQ4Js66I9RtA

//날짜, 키워드 : ?from=2026-01-01&to=2026-01-31&keyword=진행
//users/me/tasks?from=2026-01-01&to=2026-01-31
//users/me/tasks?project_id=27
//users/me/tasks?status=todo
//users/me/tasks?from=2026-01-01&to=2026-01-31&project_id=27&status=todo&assignee_id=17&keyword=TODO
