@baseUrl = http://localhost:3001

### -----------------------------------------------------------
### [1] 할 일 첨부파일 업로드 (ZIP, Excel 등 모든 파일 가능)
### -----------------------------------------------------------
# @name taskUpload
POST {{baseUrl}}/files
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="image"; filename="project_plan.png"
Content-Type: application/zip

/Users/apple/Desktop/테스트.png
------boundary--

### -----------------------------------------------------------
### [2] 프로필 이미지 업로드 (이미지 외에는 에러 발생)
### -----------------------------------------------------------
# @name profileUpload
POST {{baseUrl}}/files/profile
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="image"; filename="my_face.jpg"
Content-Type: image/jpeg

< /mnt/c/Users/USER/Desktop/man.jpg
------boundary--