@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2Nzk1NzMxOSwiZXhwIjoxNzY4MDQzNzE5fQ.rzdj2oh-us3Jy0GXJrzKXJELo2DdAVRXTrAguGcU4mQ


@invitationID = 1e31f896-89bc-4803-b43e-9d0ba451248a


// 초대 수락: 인증
// 200, 400, 404
POST {{baseUrl}}/invitations/{{invitationID}}/accept
Authorization: Bearer {{accessToken}}

// 초대 거절: 인증
###
POST {{baseUrl}}/invitations/{{invitationID}}/reject
Authorization: Bearer {{accessToken}}
// 인증만 되면 거절 가능. 초대코드 소지 자체로 인가되는 것으로 간주?

// 초대 취소: 인증, 인가
// 204, 400, 401, 403, 404
### 
DELETE {{baseUrl}}/invitations/{{invitationID}}
Authorization: Bearer {{accessToken}}
