@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NzY1OTUwMywiZXhwIjoxNzY3NzQ1OTAzfQ.8svW0RKiopc5CJzXEowLojhxsXcQDQpsCzRK6BDFYFY
###
GET {{baseUrl}}/projects
Authorization: Bearer {{accessToken}}
// 멤버 목록 조회: 인증, 인가
// 200, 400, 401, 403
###
GET {{baseUrl}}/projects/1/users  
Authorization: Bearer {{accessToken}}

// 멤버 제외: 인증, 인가
// 204, 400, 401, 403, 404
### 
DELETE {{baseUrl}}/projects/1/users/8
Authorization: Bearer {{accessToken}}
// 멤버 초대: 인증, 인가
// 201, 400, 401, 403
###
POST {{baseUrl}}/projects/1/invitations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "user4@test.com"
}